// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgKgiyYGr6G0jFtbsNssmiI2lxKVSmg8k',
    appId: '1:95366503577:web:eccad4ea89203336c3ec08',
    messagingSenderId: '95366503577',
    projectId: 'vittapet',
    authDomain: 'vittapet.firebaseapp.com',
    storageBucket: 'vittapet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuECJFlImRz3HMqxw0FS3gycg5GFojxQs',
    appId: '1:95366503577:android:29072360d01aee50c3ec08',
    messagingSenderId: '95366503577',
    projectId: 'vittapet',
    storageBucket: 'vittapet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-g9iFukZsxtIS4E6l-_w0lu7OkubeHjE',
    appId: '1:95366503577:ios:2f0b14f894875298c3ec08',
    messagingSenderId: '95366503577',
    projectId: 'vittapet',
    storageBucket: 'vittapet.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-g9iFukZsxtIS4E6l-_w0lu7OkubeHjE',
    appId: '1:95366503577:ios:2f0b14f894875298c3ec08',
    messagingSenderId: '95366503577',
    projectId: 'vittapet',
    storageBucket: 'vittapet.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgKgiyYGr6G0jFtbsNssmiI2lxKVSmg8k',
    appId: '1:95366503577:web:922dc5ee6734c625c3ec08',
    messagingSenderId: '95366503577',
    projectId: 'vittapet',
    authDomain: 'vittapet.firebaseapp.com',
    storageBucket: 'vittapet.firebasestorage.app',
  );
}
